name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - uses: lablup/sparse-checkout@main
        with:
          repository: lablup/sparse-checkout-test-repo
          patterns: |
            dir1
          token: ${{ secrets.TEST_REPO_PAT }}
