name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-test
        uses: ./
        with:
          repository: lablup/sparse-checkout-test-repo
          patterns: |
            dir1
          token: ${{ secrets.TEST_REPO_PAT }}
          path: ./test-repo
